version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      SQLALCHEMY_DATABASE_URI: postgres://postgres:postgres@db:5432/survey
    depends_on:
      - db
  db:
    image: "postgres:12.0-alpine"
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: survey

volumes:
  postgres:
