##
# This installs PostgreSQL on an Ubuntu system, creates a database and a user with access to the database.
#
---

- name: ensure packages are installed
  apt: 
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: ensure database is created
  become_user: postgres
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  become_user: postgres
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: ensure no other user can access the database
  become_user: postgres
  postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
